### ISSUE TITLE
Should we rename proto to tpmpb?

### ISSUE THREAD

**Issue by josephlr** [google/go-tpm-tools#114]
Having packages end in `pb` seems to be the standard convention.

Examples:
  - The example in the official docs: https://developers.google.com/protocol-buffers/docs/gotutorial#defining-your-protocol-format
  - All the subpackages of: https://github.com/protocolbuffers/protobuf-go/tree/master/types

Most notably, it conflicts with https://pkg.go.dev/google.golang.org/protobuf@v1.26.0/proto also called `proto`

**Comment by jkl73** [comment]
I think we should change it. Renaming the package can save us from using the tpmpb importing alias.

**Comment by alexmwu** [comment]
We already use tpmpb as an alias. Also, it's typically either {prefix}pb or just {prefix} from a random sample of google repos: https://github.com/search?p=7&q=language%3Agolang+filename%3Apb.go+org%3Agoogle&type=Code

**Comment by josephlr** [comment]
Other alternatives:
  - Keep the `proto` directory, but call the proto package `common` or `commonpb` 
  - Make a `common` package, and either have the protos directly in that package, or a subdirectory (called `proto`/`pb`/`commonpb`)
  - Split the proto into multiple subpackages, and have:
    - `proto/corepb`
    - `proto/attestationpb`
    - `proto/statepb`
    - `proto/policypb`
