### ISSUE TITLE
Build noise with Clang due to unknown flag

### ISSUE THREAD

**Issue by azdagron** [google/go-tpm-tools#154]
Clang does not implement the `-Wno-maybe-uninitialized` warning flag, which is unconditionally added during cgo compilation:

https://github.com/google/go-tpm-tools/blob/8a3510140faba068d0a038fae7a6f73c4f27a407/simulator/internal/internal_cgo.go#L20

This results in the following noise during compilation:

```# github.com/google/go-tpm-tools/simulator/internal
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
... repeated many times ...
```

It would be super nice not to get this compiler spew.

Clang version:
```
$ clang --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by josephlr** [comment]
@azdagron thanks for the report, I don't know if Go supports conditional compilation flags for clang vs GCC. IIRC this flag was added to _avoid_ compiler spew on GCC.

I can take a look at this though.

**Comment by azdagron** [comment]
Thanks for jumping on this so quickly, @josephlr!
