### ISSUE TITLE
go install for github.com/google/go-tpm-tools/cmd/gotpm no longer works

### ISSUE THREAD

**Issue by josephlr** [google/go-tpm-tools#174]
Before, the `gotpm` CLI tool could be installed with one step:
```bash
go install github.com/google/go-tpm-tools/cmd/gotpm@latest
```
However, now this gives the error:
```
go: github.com/google/go-tpm-tools/cmd/gotpm@latest (in github.com/google/go-tpm-tools/cmd@v0.0.0-20220321192342-5dafd89db1a4):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

This is because we have a `replace` directive here: https://github.com/google/go-tpm-tools/blob/5dafd89db1a42c20b4a0a1c32ced618c4be74864/cmd/go.mod#L12

The solution to this is probably to require go 1.18 and use [Workspaces](https://go.dev/ref/mod#workspaces). This should also (hopefully) solve our problems with running `go build`/`go test`/etc... We might even be able to add this now, while keeping go 1.16 for building the existing module.

**Comment by brpatel12** [comment]
Just came to post about something similar, instructions say:
```bash
cd /my/path/to/cloned/go-tpm-tools
go build ./cmd/gotpm
```
but I now get
```bash
go: directory cmd/gotpm is outside main module
```
but I had to update it to the following:
```bash
pushd go-tpm-tools/cmd
go build ./gotpm
```
I think the following also works:
```bash
pushd go-tpm-tools/cmd/gotpm
go build
```
but binary is at `cmd/gotpm/gotpm`

**Comment by josephlr** [comment]
@brpatel12 thanks for pointing this out. #181 should fix the instructions. Note that the older instructions should work now if you're using the latest branch and go 1.18
