### ISSUE TITLE
Support loading cached key

### ISSUE THREAD

**Issue by daniel-weisse** [google/go-tpm-tools#237]
Is it possible to simply load a cached key without having to know extra parameters, e.g. a template matching the key?

Basically, I want a TPM client function like the following:
```Go
// LoadKey loads a key from the provided handle.
func LoadKey(rw io.ReadWriter, handle tpmutil.Handle) (*Key, error) {
        cachedPub, _, _, err := tpm2.ReadPublic(rw, handle)
        if err != nil {
                return nil, err
        }
        k := &Key{
                rw: rw,
                handle: handle,
                pubArea: cachedPub,
        }
        return k, k.finish()
}
```

The only function that does a similar thing is `NewCachedKey`, but comes with the risk of overwriting a key at the given handle if the provided template does not match the existing key.

**Comment by alexmwu** [comment]
That would be useful. We probably won't get to it for some time, but I'd be happy to review this PR.
