### ISSUE TITLE
Issue building on Ubuntu 2204 jammy

### ISSUE THREAD

**Issue by m-kostrzewa** [google/go-tpm-tools#238]
I've been bumping a docker container from Ubuntu2004 to Ubuntu2204 and encountered the following error:

```
# github.com/google/go-tpm-tools/simulator/internal
In file included from /root/go/pkg/mod/github.com/google/go-tpm-tools@v0.2.1/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/BnValues.h:317,
                 from /root/go/pkg/mod/github.com/google/go-tpm-tools@v0.2.1/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/Global.h:82,
                 from /root/go/pkg/mod/github.com/google/go-tpm-tools@v0.2.1/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/Tpm.h:52,
                 from /root/go/pkg/mod/github.com/google/go-tpm-tools@v0.2.1/simulator/internal/internal.go:34:
/root/go/pkg/mod/github.com/google/go-tpm-tools@v0.2.1/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/Ossl/TpmToOsslMath.h:52:5: error: #error Untested OpenSSL version
   52 | #   error Untested OpenSSL version
      |     ^~~~~
```

I've only found the following related issue: https://github.com/ibm-openbmc/dev/issues/3452

Anyways, my workaround was to manually install libssl-dev_1.1.1:

```
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl-dev_1.1.1f-1ubuntu2.16_amd64.deb 
```

Are there any plans to address this issue?

**Comment by josephlr** [comment]
Right now the version of our simulator only works with OpenSSL v1, so it's required to build the code. 

We will need to update the simulator to a newer (potentially patched) version to make this work.

**Comment by josephlr** [comment]
@m-kostrzewa this particular issue was fixed in https://github.com/google/go-tpm-tools/commit/51429b623805be4a2db6f6ff3763b27d6bb36e6b so if you use go-tpm-tools v0.3.0 or later you shouldn't have this issue.

It seems like you are currently using v0.2.1

**Comment by m-kostrzewa** [comment]
Just a mention, since it may be relevant to someone. I just checked it and you're right. I've been using v0.2.1 as it's been a dependency of google/go-attestation. They have bumped go-tpm-tools dependency from v0.2.1 to v0.3.1 on Dec 9, 2021 (literally days after I first installed it :roll_eyes: ).
