### ISSUE TITLE
Simulator checks wrong path for `openssl` with Homebrew on Apple Silicon macOS

### ISSUE THREAD

**Issue by strideynet** [google/go-tpm-tools#312]
```
// // Flags to find OpenSSL installation on macOS (default Homebrew location)
// #cgo darwin CFLAGS: -I/usr/local/opt/openssl/include
// #cgo darwin LDFLAGS: -L/usr/local/opt/openssl/lib
```

The aforementioned flags are correct on Intel macOS, but on Apple Silicon, Homebrew installs packages to `/opt/homebrew/opt` rather than `/usr/local/opt`. Whilst the root directory readme in this project instructs users on how to set `C_INCLUDE_PATH`, it doesn't mention this case specifically and the Go files seem to attempt to work with Homebrew. This can be a little confusing for those less familiar with the elements in play.

Has support for `pkg-config` been considered ? This feels like a less platform dependent way of handling this and quite a few dependencies I've encountered that use cgo make use of `pkg-config` for this purpose.

### Workaround

```
export C_INCLUDE_PATH="$(brew --prefix openssl)/include"
export LIBRARY_PATH="$(brew --prefix openssl)/lib"
# Now you can run go build/go test
```

**Comment by ohkinozomu** [comment]
It was resolved in https://github.com/google/go-tpm-tools/pull/444 .
