### ISSUE TITLE
documentation: clearify if its IBM or Microsoft simulator ...

### ISSUE THREAD

**Issue by genofire** [google/go-tpm-tools#83]
In the `README.md` it is the IBM simulator linked ...
https://github.com/google/go-tpm-tools/commit/de523c4444ff9d69578766d9a7f3c598f8276a25

Should the link forward to: https://github.com/Microsoft/ms-tpm-20-ref/ ?

Is the "Microsoft Simulator" a real simulator, or just a library/wrapper to write own little simulators in unit-test?

**Comment by alexmwu** [comment]
Hi, you're right that link should be https://github.com/Microsoft/ms-tpm-20-ref/. The simulator package vends the MS simulator, which is a real simulator. We run our tests by default on the simulator rather than a real TPM.

I opened a small PR to clarify the confusion.
